name: Promote charm

on:
  workflow_dispatch:
    inputs:
      origin-channel:
        type: choice
        description: 'Origin Channel'
        options:
        - latest/edge
        - 2.2/edge
      destination-channel:
        type: choice
        description: 'Destination Channel'
        options:
        - 2.2/edge
        - 2.2/stable
    secrets:
      CHARMHUB_TOKEN:
        required: true

jobs:
  promote-charm:
    uses: canonical/operator-workflows/.github/workflows/promote_charm.yaml@main
    with:
      origin-channel: ${{ github.event.inputs.origin-channel }}
      destination-channel: ${{ github.event.inputs.destination-channel }}
    secrets: inherit
